version: '2'
services:
    adobelatlang-app:
        image: adobelatlang
        external_links:
            - adobelatlang-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/adobelatlang?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    adobelatlang-mysql:
        extends:
            file: mysql.yml
            service: adobelatlang-mysql
